name: Python sanity check and tests

on: [push]

jobs:

  python:
    name: Run tests and lint python
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # prepare environment
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - run: pip install -r requirements.txt

      # run tests
      - run: pip install pytest coverage
      - run: coverage run -m pytest --verbose
      - run: coverage report *.py

      # code style checks
      - run: pip install pycodestyle
      - run: pycodestyle .

      # type annotation checks
      - run: pip install mypy
      - run: mypy .

      # if you pretend to make a typed version of your program, you should uncomment this line:  
      # - run: mypy . --strict

  markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint markdown files
      uses: actionshub/markdownlint@main
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
